services:
  postgres:
    image: postgres:17
    restart: always
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: caluma
      POSTGRES_USER: caluma
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: "keycloak"
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_buffers=128MB
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c max_connections=100
      -c client_min_messages=warning

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: caluma
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KC_ADMIN_URL: http://localhost:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - keycloak-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data
      - ./keycloak/realms:/opt/keycloak/data/import:ro
    command: >
      start-dev
      --features=scripts,organization,admin-api,authorization
      --import-realm

  caluma:
    image: ghcr.io/projectcaluma/caluma:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=caluma
      - DATABASE_USER=caluma
      - DATABASE_PASSWORD=admin
      - SECRET_KEY=change-me-in-production
      - ALLOWED_HOSTS=*
      # OIDC/Keycloak Configuration
      - OIDC_USERINFO_ENDPOINT=http://host.docker.internal:8080/realms/duva/protocol/openid-connect/userinfo
      - OIDC_VERIFY_SSL=false
      # Permission & Visibility Classes (scope-based)
      - VISIBILITY_CLASSES=caluma.caluma_core.visibilities.Any
      - PERMISSION_CLASSES=caluma.caluma_user.permissions.IsAuthenticated
    networks:
      - keycloak-network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
